import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  Apple,
  Archive,
  Award,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Brush,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  Users,
  ClipboardList,
  Cloud,
  Code2,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Dumbbell,
  Factory,
  FileText,
  Film,
  Flag,
  Flame,
  Flower2,
  FolderKanban,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  Home,
  Image,
  Key,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Package,
  Palette,
  PenLine,
  Phone,
  Plane,
  Puzzle,
  Rocket,
  School,
  Server,
  Settings,
  Shield,
  Ship,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Sun,
  Target,
  Tent,
  Timer,
  Trophy,
  Truck,
  Utensils,
  Video,
  Wallet,
  Waves,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

export const PROJECT_ICON_CATALOG: { id: string; icon: LucideIcon }[] = [
  { id: "folder", icon: FolderKanban },
  { id: "monitor", icon: Monitor },
  { id: "smartphone", icon: Smartphone },
  { id: "globe", icon: Globe },
  { id: "code", icon: Code2 },
  { id: "palette", icon: Palette },
  { id: "chart", icon: BarChart3 },
  { id: "briefcase", icon: Briefcase },
  { id: "chat", icon: MessageCircle },
  { id: "home", icon: Home },
  { id: "building", icon: Building2 },
  { id: "store", icon: Store },
  { id: "factory", icon: Factory },
  { id: "landmark", icon: Landmark },
  { id: "school", icon: School },
  { id: "rocket", icon: Rocket },
  { id: "plane", icon: Plane },
  { id: "car", icon: Car },
  { id: "truck", icon: Truck },
  { id: "ship", icon: Ship },
  { id: "bike", icon: Bike },
  { id: "map", icon: Map },
  { id: "pin", icon: MapPin },
  { id: "compass", icon: Compass },
  { id: "users", icon: Users },
  { id: "mail", icon: Mail },
  { id: "phone", icon: Phone },
  { id: "bell", icon: Bell },
  { id: "megaphone", icon: Megaphone },
  { id: "calendar", icon: Calendar },
  { id: "clock", icon: Timer },
  { id: "alarm", icon: AlarmClock },
  { id: "star", icon: Star },
  { id: "heart", icon: Heart },
  { id: "sparkles", icon: Sparkles },
  { id: "zap", icon: Zap },
  { id: "flame", icon: Flame },
  { id: "sun", icon: Sun },
  { id: "moon", icon: Moon },
  { id: "cloud", icon: Cloud },
  { id: "leaf", icon: Leaf },
  { id: "flower", icon: Flower2 },
  { id: "mountain", icon: Mountain },
  { id: "waves", icon: Waves },
  { id: "tent", icon: Tent },
  { id: "camera", icon: Camera },
  { id: "image", icon: Image },
  { id: "film", icon: Film },
  { id: "video", icon: Video },
  { id: "music", icon: Music },
  { id: "headphones", icon: Headphones },
  { id: "mic", icon: Mic },
  { id: "game", icon: Gamepad2 },
  { id: "puzzle", icon: Puzzle },
  { id: "trophy", icon: Trophy },
  { id: "award", icon: Award },
  { id: "flag", icon: Flag },
  { id: "target", icon: Target },
  { id: "lightbulb", icon: Lightbulb },
  { id: "book", icon: BookOpen },
  { id: "bookmark", icon: Bookmark },
  { id: "newspaper", icon: Newspaper },
  { id: "graduation", icon: GraduationCap },
  { id: "cpu", icon: Cpu },
  { id: "database", icon: Database },
  { id: "server", icon: Server },
  { id: "wifi", icon: Wifi },
  { id: "settings", icon: Settings },
  { id: "wrench", icon: Wrench },
  { id: "hammer", icon: Hammer },
  { id: "lock", icon: Lock },
  { id: "key", icon: Key },
  { id: "shield", icon: Shield },
  { id: "layers", icon: Layers },
  { id: "box", icon: Box },
  { id: "package", icon: Package },
  { id: "gift", icon: Gift },
  { id: "shopping", icon: ShoppingBag },
  { id: "wallet", icon: Wallet },
  { id: "card", icon: CreditCard },
  { id: "banknote", icon: Banknote },
  { id: "calculator", icon: Calculator },
  { id: "clipboard", icon: ClipboardList },
  { id: "file", icon: FileText },
  { id: "archive", icon: Archive },
  { id: "link", icon: Link },
  { id: "pen", icon: PenLine },
  { id: "brush", icon: Brush },
  { id: "coffee", icon: Coffee },
  { id: "utensils", icon: Utensils },
  { id: "apple", icon: Apple },
  { id: "activity", icon: Activity },
  { id: "dumbbell", icon: Dumbbell },
  { id: "gem", icon: Gem },
];

export function getProjectLucideIcon(id: string): LucideIcon {
  return PROJECT_ICON_CATALOG.find((item) => item.id === id)?.icon || FolderKanban;
}
